rag_config_path: "../rag/config.yaml"
graphs_root: "../rag/kgs"
default_top_k: 8
default_top_m: 2
summary:
  model: "gpt-4o-mini"
  max_chunks: 4
  max_chars_per_chunk: 600
  prompt: |
    You are a helpful assistant that writes short overviews of knowledge graphs. Mention the
    domain focus, the kinds of entities/relationships captured, and the typical questions the
    graph can answer. Aim for 4-6 sentences and avoid verbatim copying from the excerpts.
app:
  cors_origins:
    - "*"
  auth_required: false
