# Minimal config for the rag toolkit

run_id: hackathon_demo
cache_root: "./cache"          # resolves relative to this folder
logs_path: "./cache/hi"        # index.json goes here

main_rag: "hi"

default_embedding:
  class: openai
  model: text-embedding-3-small

modes:
  hi:
    mode: hi
    top_k: 4
    enable_naive_rag: true
    chunk_prefix_len: 120
    chunk_token_size: 1400
    chunk_overlap_token_size: 150
    tiktoken_model_name: "gpt-4o"
    node_hit_strategy: "union"
    graph_cluster_algorithm: "leiden"
    max_graph_cluster_size: 10
    graph_cluster_seed: 3735928559
    node_embedding_algorithm: "node2vec"
    node2vec_params:
      dimensions: 1536
      num_walks: 10
      walk_length: 40
      window_size: 2
      iterations: 3
      random_seed: 3
    enable_hierachical_mode: true
    log_level: 20
