name: Publish backend & frontend to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            image: ghcr.io/ahmaddabbass/grace-backend
            context: .
            file: ./Dockerfile
          - name: frontend
            image: ghcr.io/ahmaddabbass/grace-frontend
            context: ./kgx-ui
            file: ./kgx-ui/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ matrix.image }}:latest
